# Generated by Django 5.1 on 2024-09-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.DurationField(blank=True, null=True, verbose_name='tiempo invertido'),
        ),
    ]
