# Generated by Django 5.1 on 2025-02-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified",
                        verbose_name="modified",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                ("description", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("OP", "OPEN"), ("CL", "CLOSED")],
                        default="OP",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "db_table": "commissions",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified",
                        verbose_name="modified",
                    ),
                ),
                (
                    "deleted",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="deleted"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                ("path", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "documents",
            },
        ),
    ]
