# Generated by Django 5.1 on 2025-02-07 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified')),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OP', 'OPEN'), ('CL', 'CLOSED')], default='OP', max_length=2)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commisions',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified')),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True, verbose_name='deleted')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('path', models.CharField(max_length=255)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='commissions.commission')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['id', 'active'], name='commisions_id_d532f5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['id', 'active'], name='documents_id_2c4ffe_idx'),
        ),
    ]
