# Generated by Django 5.1 on 2025-02-12 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0001_initial"),
        ("petitions", "0002_remove_petition_parent_petition_petition_is_main_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="petition",
            field=models.ForeignKey(
                limit_choices_to={"is_main": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to="petitions.petition",
            ),
        ),
    ]
