# Generated by Django 5.1 on 2025-02-07 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commissions", "0001_initial"),
        ("petitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commission",
            name="petition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to="petitions.petition",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="document",
            name="commission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comissions",
                to="commissions.commission",
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["id", "active"], name="commissions_id_b0137d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["id", "active"], name="documents_id_2c4ffe_idx"),
        ),
    ]
