# Generated by Django 5.1 on 2025-02-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petition",
            name="parent_petition",
        ),
        migrations.AddField(
            model_name="petition",
            name="is_main",
            field=models.BooleanField(default=True, verbose_name="Is main petition"),
        ),
        migrations.AlterField(
            model_name="petition",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="petition",
            name="title",
            field=models.CharField(max_length=120, verbose_name="Title"),
        ),
    ]
