# Generated by Django 5.1 on 2025-02-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="status_approval",
            field=models.CharField(
                choices=[
                    ("WT", "WAITING"),
                    ("AP", "APPROVED"),
                    ("NP", "NOT_APPROVED"),
                    ("DN", "DONE"),
                ],
                default="WT",
                max_length=2,
            ),
        ),
    ]
