# Generated by Django 5.1 on 2025-01-20 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commissions", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified",
                        verbose_name="modified",
                    ),
                ),
                ("deleted", models.DateTimeField(default=None, verbose_name="deleted")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="Petition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified",
                        verbose_name="modified",
                    ),
                ),
                ("deleted", models.DateTimeField(default=None, verbose_name="deleted")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("title", models.CharField(max_length=120, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LW", "LOW"),
                            ("MD", "MEDIUM"),
                            ("HG", "HIGH"),
                            ("UG", "URGENT"),
                            ("SU", "SUPER_URGENT"),
                            ("ST", "STANDART"),
                        ],
                        default="LW",
                        max_length=2,
                    ),
                ),
                (
                    "status_approval",
                    models.CharField(
                        choices=[
                            ("WT", "WAITING"),
                            ("AP", "APPROVED"),
                            ("NP", "NOT_APPROVED"),
                        ],
                        default="WT",
                        max_length=2,
                    ),
                ),
                (
                    "commission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committees_on_petitions",
                        to="commissions.commission",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="petitions.department",
                    ),
                ),
                (
                    "human_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.humanresource",
                    ),
                ),
                (
                    "parent_petition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_petitions",
                        to="petitions.petition",
                        verbose_name="parent petition",
                    ),
                ),
            ],
            options={
                "db_table": "petitions",
            },
        ),
        migrations.CreateModel(
            name="PetitionsAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified",
                        verbose_name="modified",
                    ),
                ),
                ("deleted", models.DateTimeField(default=None, verbose_name="deleted")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("path", models.CharField(max_length=255)),
                (
                    "petition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="petitions.petition",
                    ),
                ),
            ],
            options={
                "db_table": "petition_attachment",
            },
        ),
    ]
