# Generated by Django 5.1 on 2025-02-13 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanresource',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hr_companies', to='petitions.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='humanresource',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_departments', to='petitions.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, help_text='Set to true when the user have verified its email address. ', verbose_name='verified'),
        ),
    ]
