# Generated by Django 5.1 on 2025-02-11 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanresource',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='human_resource', to=settings.AUTH_USER_MODEL),
        ),
    ]
