# Generated by Django 5.1 on 2025-02-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0004_alter_petition_department_and_more'),
        ('users', '0002_humanresource_company_humanresource_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_clients', to='petitions.company')),
                ('human_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_companies', to='users.humanresource')),
            ],
            options={
                'unique_together': {('human_resource', 'company')},
            },
        ),
    ]
