# Generated by Django 5.1 on 2024-09-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours',
            field=models.TimeField(blank=True, null=True, verbose_name='tiempo'),
        ),
    ]
